### PR TITLE
Removed OpenGL add Vulkan support to faqs and index

### PR DESCRIPTION
**Pull request by drillsar**
OpenGL no longer supported and faq; index pages; about fixed.
Fixed issue #723

### CODE REVIEW

**Comment by Razzile** [comment]
this is your 3rd account now as well.

**Comment by Margen67** [comment]
Here's a list of all of his PRs:
01. #715
02. #716
03. #717
04. #719
05. #720
06. #721
07. #722 (merged)
08. #725
09. #726
10. #727
11. #728
12. #729
13. #731
14. #734
15. #736 
16. (Probably coming soon)

**Comment by drillsar** [comment]
I have an issue with my original fork for some reason gh-pages is on master. If and when that PR is merged I will delete that fork.

**Comment by hlide** [comment]
@drillsar if you have issue with one fork, you simply need to delete it and re-fork from the original without changing account. Hope you delete your previous accounts and their forks so that they should not pollute GitHub with useless stuff.

**Pull request merged**
