### PR TITLE
Redo the AMD fix with a clean fork

### PR DESCRIPTION
**Pull request by shadowbrony33**
- Changed the Depth and Texture formats from 24-bit to 32-bit
- Unlocked XBLA content (remove this)

Issues:
- Sonic 06 renders everything invisible ( This issue is not present on Nvidia GPUs ), everything else works fine
- OpenGL does not work on AMD

Some help from @DrChat or @gibbed would be greatly appreciated.

### CODE REVIEW

**Comment by gibbed** [comment]
Regardless of the other changes, the license mask change will not be accepted.

**Comment by shadowbrony33** [comment]
noted

**Comment by shadowbrony33** [comment]
If this gets merged, make sure to close #774

**Comment by shadowbrony33** [comment]
@gibbed what is going on with Travis CI?

**Comment by gibbed** [comment]
@shadowbrony33 Lint is failing because of bad code formatting.

**Comment by shadowbrony33** [comment]
xb format comes up with nothing

**Comment by shadowbrony33** [comment]
@gibbed 
> runs "xb format" *no changes*
>run the clang auto format for VS (set to Google style) *Travis CI still fails*

Amazing...

**Comment by shadowbrony33** [comment]
@gibbed Finally fixed my crappy formatting

https://travis-ci.org/benvanik/xenia/builds/262502423

**Comment by shadowbrony33** [comment]
I'm going to close this pull request for a while.

**Pull request closed without merging**
