### PR TITLE
xenia New icone

### PR DESCRIPTION
**Pull request by KDZL**
https://github.com/benvanik/xenia/issues/811#issuecomment-349468986

### CODE REVIEW

**Comment by KDZL** [comment]
esboco 2

**Comment by gibbed** [comment]
Nope.

**Comment by KDZL** [comment]
https://github.com/KDZ12/xenia/commit/a49afe2cff0427828759d622dbfcfe2e8f2b9e03

**Comment by KDZL** [comment]
Okay, what's up?

**Comment by gibbed** [comment]
1. Opening numerous (11!) nonsense PRs with no communication on your behalf about what you are doing.
2. Ignoring communication from me when told to stop and explain what you're doing.
3. Continuing to open (2) nonsense PRs.

All you've done is irritate the contributors with work to clean up after you. You've left my good graces and I'll not tolerate anything further from you.

**Comment by Xephorium** [comment]
Also, I definitely created these icons and would like to be the one to render them out at appropriate resolution/transparency and commit if the main devs like the art direction.

**Pull request closed without merging**
