### PR TITLE
Update texture_cache.cc

### PR DESCRIPTION
**Pull request by KDZL**
src/xenia/gpu/vulkan/texture_cache.cc

### CODE REVIEW

**Comment by DrChat** [comment]
? Not sure what this PR is intended to do, closing.

**Comment by Razzile** [comment]
@DrChat there's been quite a few accounts lately making nonsensical PRs on repos (especially emulator repos)

**Comment by DrChat** [comment]
@Razzile Yeah, I've noticed that on the game compat repo.
I don't think @KDZL is a "nonsenical account", just someone that has some learning to do on PRs.

**Comment by Margen67** [comment]
@DrChat https://github.com/benvanik/xenia/issues/1096
https://github.com/KDZL
If you look at his history you can see he has also made garbage PRs for other repos.
https://github.com/slashiee/cemu_graphic_packs/pull/206
https://github.com/slashiee/cemu_graphic_packs/pull/204
https://github.com/slashiee/cemu_graphic_packs/pull/202

**Pull request closed without merging**
