### PR TITLE
Allow computers with non-latin native codepages to build the project.

### PR DESCRIPTION
**Pull request by TheCubeMaster019**
Thanks to @yxmline from #812 
As someone with a Japanese copy of Windows, I need this change to build the project.

### CODE REVIEW

**Comment by TheCubeMaster019** [comment]
Hmm... this commit seems to introduce a lot of warnings about "ignoring option '/utf8'", but the build DOES pass... OH! I have to use 'utf-8'...

**Comment by TheCubeMaster019** [comment]
Now it's just one commit~

**Comment by rlabrecque** [comment]
Can you fix your tab > spaces?

**Comment by TheCubeMaster019** [comment]
oops! sure thing~

**Comment by DrChat** [comment]
Looks pretty good to me - and from testing I'm not noticing any adverse effects. Merged!

**Pull request merged**
