### PR TITLE
Update shim conversion on some files

### PR DESCRIPTION
**Pull request by Megamouse**
Hi, I hope I understood everything correctly. Feel free to add any comments and please be nitpicky :)

xam_info.cc
xam_msg.cc
xam_notify.cc
xboxkrnl_memory.cc
xboxkrnl_misc.cc

### CODE REVIEW

**Comment by Megamouse** [comment]
oh shoot, I think I forgot to format the lines for max.80 chars

**Comment by gibbed** [comment]
Looks alright, but you definitely didn't lint/format (which you should do).

**Comment by Megamouse** [comment]
whats the easiest way to do this?

**Comment by gibbed** [comment]
Read through the [style guide](https://github.com/benvanik/xenia/blob/master/docs/style_guide.md).

**Comment by Megamouse** [comment]
It should be formatted now.

**Comment by DrChat** [comment]
Awesome changes! 👍

**Pull request merged**
