### PR TITLE
Prevent race condition during emulator startup (issue #702)

### PR DESCRIPTION
**Pull request by parkerlamb**
The menu bar on the main window is now greyed out until the emulator is completely initialized.

This is a slightly hacky fix, it would probably be better to make the dependency between the emulator and the window one-way so a proper wait can be done during the initialization phase. However, currently they are both pretty entangled so I'm not sure that'd be worth doing until Xenia has a more permanent UI.

Fixes issue #702

### CODE REVIEW

**Comment by parkerlamb** [comment]
Turns out this was two separate race conditions, I somehow didn't hit the on_launch() problem during testing...

Leaving the fixes as two separate commits (since they are technically different problems), I can squash if need be.

**Comment by drillsar** [comment]
@parkerlamb I don't want to hijack this thread, but I used PVS Studio analyzer and a lot of errors show up. One error that caught my eye was this:
V780: The object 'out_info' of a non-passive (non-PDS) type cannot be initialized using the memset function. filesystem_win.cc 164

```
bool GetInfo(const std::wstring& path, FileInfo* out_info) {
  std::memset(out_info, 0, sizeof(FileInfo)); //V780 error on this line
  WIN32_FILE_ATTRIBUTE_DATA data = {0};
  if (!GetFileAttributesEx(path.c_str(), GetFileExInfoStandard, &data)) {
    return false;
  }

**Comment by parkerlamb** [comment]
Did those changes, Window is now passed instead of NativeWindowHandle.

**Comment by DrChat** [comment]
Excellent - thanks for the changes!

**Pull request merged**
