### PR TITLE
Shim Conversion xam_content.cc

### PR DESCRIPTION
**Pull request by tmccaff**
Still work needs to be done; I wasn't sure how to do them all.
#631

### CODE REVIEW

**Comment by maxton** [comment]
Your code does not follow the style guide. You need to format your code with `xb format` before committing.

Also, please stop opening and closing PRs. You can just add new commits to existing ones and squash them later. Constantly creating and closing PRs really hurts the notification signal-to-noise ratio for all watchers.

**Comment by tmccaff** [comment]
@maxton I did xb format and says no modified files to format.

**Comment by maxton** [comment]
`xb format` works on staged, uncommitted files.

**Comment by tmccaff** [comment]
My whole repository was messed up

**Pull request closed without merging**
