### PR TITLE
 Vulkan Atualize o carregador para o SDK 1.1.70.1

### PR DESCRIPTION
**Pull request by KDZL**

### CODE REVIEW

**Comment by gibbed** [comment]
@KDZL If you do not stop spamming us with nonsense PR updates, you will be blocked from the project.

**Comment by gibbed** [comment]
I see your thumbs down response.

If these are legitimate PRs then explain what you are doing and why it requires you to spam us with them. Otherwise, you will be blocked.

**Comment by gibbed** [comment]
Closing the PR does not count.

If you submit any further PRs without explaining what you're doing, it will be considered as ignoring my request and you will be blocked.

**Comment by hlide** [comment]
Not only that. Using English in commit message should be mandatory.

**Pull request closed without merging**
