### PR TITLE
Adding missing param name in NtAllocateVirtualMemory

### PR DESCRIPTION
**Pull request by Nukem9**

### CODE REVIEW

**Comment by DrChat** [comment]
Awesome - though I'm working on this function right now. Will incorporate these changes when I commit my own.

**Comment by Nukem9** [comment]
If you're working on the function - I also wrote this a while ago (for reference): https://github.com/xenia-project/game-compatibility/issues/268

**Comment by DrChat** [comment]
Indeed - I'm fixing that now.

**Comment by DrChat** [comment]
Incorporated into 54ba3480e471cc9d2fb8833c043d83725ebee70e.

**Pull request closed without merging**
