### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by Kriskras99**
This adds support for Python 3 in `xenia-build`. I also enforced the [Google Python Styleguide](https://google.github.io/styleguide/pyguide.html).

I currently have no access to a Windows machine so I'm relying on the AppVeyor tests.

### CODE REVIEW

**Comment by spiringmovie** [comment]
i am unable to open the emulator. it is saying that i do not have MSVCP140D.dll, VCRUNTIME140D.dll, and ucrtbased.dll. Can you add those files to this build please

**Comment by VHGaming** [comment]
why isn't there a build that we can use yet

**Comment by drillsar** [comment]
Are you saying this isn't building?

**Comment by drillsar** [comment]
I think also the xb.bat file needs to be updated to work with this. Also why not just use f not sys.version_info[:2] >= (2, 7): instead

**Comment by drillsar** [comment]
I did the changes now receive this errors:

C:\Users\Tom\Documents\xenia>xb build
Traceback (most recent call last):
  File "xenia-build", line 1345, in <module>
    main()
  File "xenia-build", line 46, in main
    vs_version = import_vs_environment()
  File "xenia-build", line 101, in import_vs_environment
    tools_path = os.path.join(candidate_path, 'vc\\auxiliary\\build\\vcvarsall.bat')
  File "C:\python35\lib\ntpath.py", line 113, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\python35\lib\genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

**Comment by Kriskras99** [comment]
Python 3 changed the default behavior of `subprocess.check_output` to return bytes and let the application deal with the encoding. It should be fixed now.

**Comment by drillsar** [comment]
still getting same errors; tried with python 3.6.
```
C:\Users\Tom\Documents\xenia>xb build
Traceback (most recent call last):
  File "xenia-build", line 1345, in <module>
    main()
  File "xenia-build", line 46, in main
    vs_version = import_vs_environment()
  File "xenia-build", line 101, in import_vs_environment
    tools_path = os.path.join(candidate_path, 'vc\\auxiliary\\build\\vcvarsall.bat')
  File "C:\python36\lib\ntpath.py", line 114, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\python36\lib\genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by drillsar** [comment]
not sure why it's doing this

**Comment by Kriskras99** [comment]
I see the problem, universal_newlines should be True, probably my autocomplete messing about.

**Comment by Kriskras99** [comment]
Could you test again?

**Comment by drillsar** [comment]
@Kriskras99 Yes I will shortly.

**Comment by legoj15** [comment]
@drillsar I don't think Travis has the right version of Python, looking at the errors

**Comment by drillsar** [comment]
@Kriskras99 perhaps travis.yml should be python 3.4 instead of python3 not sure if that would fix the error though

**Comment by Kriskras99** [comment]
I found my error, the shebang is still python 2

**Comment by Kriskras99** [comment]
It finally works, but the commit history is a bit messed up. I will try to squash the commits and then it should be ready for merging.

**Comment by DrChat** [comment]
Is this still backwards compatible with python 2?

**Comment by drillsar** [comment]
@DrChat I don't think it is. I think it was taken out.

**Comment by DrChat** [comment]
One more thing: It appears that [there are a couple of scripts you may have missed](https://github.com/benvanik/xenia/search?utf8=%E2%9C%93&q=%23%21%2Fusr%2Fbin%2Fenv+python&type=). Could you look those over and make sure they're working okay?
Especially the premake script - that's important for bootstrapping premake.

**Comment by Kriskras99** [comment]
This is indeed not Python 2 compatible, but can be changed very easily. I did miss the other scripts and will change those too but because I'm on vacation right now with spotty internet and only a chromebook to work on this might take a while.

**Comment by drillsar** [comment]
@Kriskras99 I can fix those the only thing I can't fix is the third_party clang not sure how to do that third party stuff. I fixed it already, but I can't seem to do a pull request to your fork.

**Comment by DrChat** [comment]
@Kriskras99 No problem - it'd be cool if we can make these scripts compatible with both versions. Don't worry about it for now - enjoy the vacation!

**Comment by Kriskras99** [comment]
@drillsar You can just change the clang-format-diff.py according to the license, you might also want to open a pull request upstream but that's not necessary. Are you trying to merge the python3-patch branch? Because that branch has no commits, did you push your local changes to Github?

@DrChat will do, thank you!

**Comment by drillsar** [comment]
@Kriskras99 I am about to push commits to that branch yes

**Comment by drillsar** [comment]
Should be there now

**Comment by Kriskras99** [comment]
Could you rebase to my branch, otherwise there are is a merge conflict

**Comment by shadowbrony33** [comment]
Good to see that this has finally been resolved.

**Comment by drillsar** [comment]
@Kriskras99 Ok give me a few

**Comment by drillsar** [comment]
@Kriskras99 Is it ok now?

**Comment by Kriskras99** [comment]
Yes. Now it only needs testing, and I'm pretty sure clang-format-diff.py will fail, because if the old-style print statements.

**Comment by drillsar** [comment]
tools/diff.py has /usr/bin/python as shebang is that correct? isn't it supposed to be python3?

**Comment by Kriskras99** [comment]
It is correct, that file is Python 2 and 3 compatible, so it will use the system default python (Python 3 on ArchLinux, Python 2 on most other distros)

**Comment by spiringmovie** [comment]
how would we get roms for the emulator without illegally bypassing the copy
protection

**Comment by Kriskras99** [comment]
@spiringmovie Could you please stop spamming the pull request with questions not relevant to it?

**Comment by spiringmovie** [comment]
i am asking a valid question ok

**Comment by DrChat** [comment]
@spiringmovie You're asking a valid question that's off-topic here. Try [xenia's subreddit](https://www.reddit.com/r/xenia/).

**Comment by spiringmovie** [comment]
thank you @DrChat

**Comment by spiringmovie** [comment]
this is the last time i am posting on the page, but could it be possible to
have direct playabillity to xbox 360 disks

**Comment by spiringmovie** [comment]
no software needed

**Pull request merged**
