### PR TITLE
Shim Conversion

### PR DESCRIPTION
**Pull request by tmccaff**
Still work needs to be done; I wasn't sure how to do them all. #631

### CODE REVIEW

**Comment by gibbed** [comment]
Stop closing your pull requests and opening new ones for the same thing! You have now opened and closed **_NINE_** pull requests over the last several days.

I appreciate that you want to contribute, but **_you are spamming us with notifications_**. I hate to have to say this, but if you continue to do this I **_will block you from the xenia project_**.

Do not open a pull request until you are happy with the changes you want to suggest being merged into the master.

**Comment by drillsar** [comment]
Ok sorry about that. I haven't used github in awhile and figured I did something wrong.

**Comment by tmccaff** [comment]
@gibbed sorry about that. I think made a mistake pushing the commit without formatting first, I don't know how to resubmit it now with it formatted. Also I have a quick question maybe you can answer it.
The following code to convert?
```
if (user_index == 0) {
    const auto& user_profile = kernel_state->user_profile();
    SHIM_SET_MEM_64(info_ptr + 0, user_profile->xuid());
    SHIM_SET_MEM_32(info_ptr + 8, 0);  // maybe zero?
    SHIM_SET_MEM_32(info_ptr + 12, user_profile->signin_state());
    SHIM_SET_MEM_32(info_ptr + 16, 0);  // ?
    SHIM_SET_MEM_32(info_ptr + 20, 0);  // ?
    char* buffer = reinterpret_cast<char*>(SHIM_MEM_ADDR(info_ptr + 24));
    std::strcpy(buffer, user_profile->name().data());
    SHIM_SET_RETURN_32(0);
  } else {
    SHIM_SET_RETURN_32(X_ERROR_NO_SUCH_USER);
  }
}

**Comment by gibbed** [comment]
@tmccaff All you have to do is push new commits to the same branch that you made your pull request from. It will update the pull request automatically.

**Pull request closed without merging**
