### PR TITLE
Detect OpenGL 4.60

### PR DESCRIPTION
**Pull request by Kitessencial**
This change allows Xenia to detect if the system has OpenGL 4.6

### CODE REVIEW

**Comment by joaozin23** [comment]
Not ah that problem aki n

**Comment by raynebc** [comment]
Consider using my previous suggestion of:
if ((glsl_version.find("4.5") != 0) && (glsl_version.find("4.6") != 0))

Which should work with OpenGL 4.5x and 4.6x instead of just 4.50 and 4.60

**Comment by Kitessencial** [comment]
Indeed, it is a better approach. I didn't know they were versions between 4.50 and 4.60.

**Comment by x1nixmzeng** [comment]
Tiny nitpick, but a find result of 0 is a valid index. `std::string::npos` is defined as `-1` when the string is not found.

**Comment by maxton** [comment]
@x1nixmzeng - I think the code is correct as-is; the version number will always be at the start of the string so checking for `!= 0` is equivalent to checking for `== -1` in this case

**Comment by Kitessencial** [comment]
True, the code should work fine as is, the current release uses != 0.
But, for clarity, I think it's better to adopt the == -1, maybe a new OpenGL version is added in the future that changes how the string starts, so it would be easier to add detection for it as well.

**Comment by gibbed** [comment]
You should be comparing the index against std::string::npos, not -1 (even if npos is technically -1).

**Comment by Kitessencial** [comment]
You mean like this?

**Pull request merged**
