### PR TITLE
Minecraft fixes

### PR DESCRIPTION
**Pull request by DrChat**
* Holy shit, minecraft now goes ingame with this! (xenia-project/game-compatibility#29) 

* Potential to fix other games that hung on loading screens (ones that monitor thread exit codes to signal load finished)
 * Fixes BF1943 hang on loading screen

### CODE REVIEW

**Comment by raven02** [comment]
@DrChat , just wonder did u get this screen when boot up .Once i press 'exit' and then assert with ignore , it crashed,

minecraft

**Comment by gibbed** [comment]
If you're trying to run a patched copy of the game, that probably won't work since we don't support the update filesystem yet.

**Comment by raven02** [comment]
I see .Thanks glibbed.

**Comment by gibbed** [comment]
No, it could mean any number of things.

**Comment by raven02** [comment]
I see.If my one is patched , i think there should no other way round to run unless the update filesystem function got implemented?

**Pull request merged**
