### PR TITLE
Added GPU register definitions

### PR DESCRIPTION
**Pull request by parkerlamb**
These are some definitions for unknown GPU registers, mostly taken from [libxenon](https://github.com/Free60Project/libxenon/blob/master/libxenon/drivers/xenos/xenos.h). These seem to be correct, judging on what libxenon does with them and from where they show up in Xenia logs. They have not been hardware-tested, however.

Note: libxenon's register offsets are defined 4 times larger than their actual values, it has macros which automatically divide by 4 for each access. I imagine this was done so the offsets would line up with the publicly available AMD docs. Xenia uses the actual offsets so the division has already been done here.

### CODE REVIEW

**Comment by DrChat** [comment]
Nice find! I didn't realize libxenon's register offsets were multiplied by 4.

**Comment by tmccaff** [comment]
I found this one as well:
00000004 GPU: Write to unknown register (045E = 00000004) Any definition for this?

**Comment by tmccaff** [comment]
@parkerlamb I am trying to look at libxenon code for missing registers and how you did it? I am new to this example in my log file I have  have w> 00000004 GPU: Write to unknown register (1973 = 00010000)

According to this it's AVIVO_D1SCL_UPDATE. How did you achieve that? I am trying to find out some more unknown registers and like to help. Thanks

**Comment by parkerlamb** [comment]
@tmccaff In your example, Xenia is trying to write to register 0x1973. Libxenon's register offsets are defined as 4 times larger than they actually are - because Xenia does not do this we need to multiply the unknown offset by 4. So, 0x1973 * 0x4 = 0x65CC. Libxenon defines 0x65CC as AVIVO_D1SCL_UPDATE.

Libxenon's register definitions are all (I think) in the file I linked in the PR description. If you google the register names you can usually find AMD docs which explain what they do.

A word of warning - as DrChat has mentioned in #610, most of these registers aren't useful. They generally just expose internal GPU state which isn't being emulated anyway. Defining them is certainly helpful but at this stage doesn't do much more than eliminate log spam.

Good luck!

**Comment by goedzo** [comment]
Not sure if it is fully related, but actually got a crash dump after writing to an unkown register.

Game -> Alone in the dark. Crashes immediately after booting into the game.

Here's the snipet of the log, before and after the crash:

> G> 00000004 Creating pipeline 297CEFCB3422E4F6, VS 8F4ECF10C53859FE
> G> 00000004 Resolve: (0,0)->(1040,600) of RT 0 (pitch 1040, 1 sample, format 3) at 0
> G> 00000004 Resolve: Copying samples 0 to 0x19A91000 (1056x600), destination format k_8_8_8_8, exponent bias 0, red and blue swapped
> G> 00000004 Resolve: Copying via drawing
> G> 00000004 Created 1040x608 color render target with format 3
> G> 00000004 RT Cache: Full update - pitch 640, samples 2, RTs to attach 16
> G> 00000004 Created 1280x2048 depth render target with format 0
> G> 00000004 RT Depth: base 0, format 0
> G> 00000004 Generated vertex shader (96b) - hash 2C4B9E783E6EF956:
> /*    0.0 */       exec 
> /*    3   */          nop
> /*    0.1 */       alloc interpolators
> /*    1.0 */       exec 
> /*    4   */          max o0._, r0, r0
> /*    1.1 */       alloc position
> /*    2.0 */       exec 
> /*    5   */          max oPos.0001, r1, r1
> /*    2.1 */       exece 
> /*    6   */          nop
> 
> G> 00000004 Resolve: (0,0)->(1280,720) of RT 0 (pitch 1280, 1 sample, format 0) at 0
> G> 00000004 Resolve: Copying samples 0 to 0x196F9000 (1280x720), destination format k_8_8_8_8, exponent bias 0, red and blue swapped
> G> 00000004 Resolve: Copying using a compute shader
> G> 00000004 Resolve: Clearing the color render target
> i> 00000004 XE_SWAP
> G> 00000004 Created tiled 1280x720x1 2D k_8_8_8_8 texture with 1 unpacked mip level, base at 0x196F9000 (size 3768320), mips at 0x00000000 (size 0)
> G> 00000004 Loaded tiled 1280x720x1 2D k_8_8_8_8 texture with 1 unpacked mip level, base at 0x196F9000 (size 3768320), mips at 0x00000000 (size 0)
> w> 00000004 GPU: Write to unknown register (1E4E = 00000000)
> !> 00000028 ==== CRASH DUMP ====
> !> 00000028 Thread ID (Host: 0x00004F9C / Guest: 0x00000006)
> !> 00000028 Thread Handle: 0x00000028
> !> 00000028 PC: 0x82137B74
> !> 00000028 Registers:
> !> 00000028  r0   = 0x0000000000000000
> !> 00000028  r1   = 0x00000000401CEC70
> !> 00000028  r2   = 0x0000000000000000
> !> 00000028  r3   = 0x0000000000000000
> !> 00000028  r4   = 0x00000000401CEDD0
> !> 00000028  r5   = 0x00000000401CED40
> !> 00000028  r6   = 0x0000000000000000
> !> 00000028  r7   = 0x0000000000000000
> !> 00000028  r8   = 0x0000000000000020
> !> 00000028  r9   = 0x000000008206A0B8
> !> 00000028  r10  = 0x0000000000000000
> !> 00000028  r11  = 0x0000000000000000
> !> 00000028  r12  = 0x0000000082138430
> !> 00000028  r13  = 0x000000000003C000
> !> 00000028  r14  = 0x0000000000000000
> !> 00000028  r15  = 0x0000000000000000
> !> 00000028  r16  = 0x0000000000000000
> !> 00000028  r17  = 0x0000000000000000
> !> 00000028  r18  = 0x0000000000000000
> !> 00000028  r19  = 0x0000000000000000
> !> 00000028  r20  = 0x0000000000000000
> !> 00000028  r21  = 0x0000000000000000
> !> 00000028  r22  = 0x0000000000000000
> !> 00000028  r23  = 0xFFFFFFFF8206A064
> !> 00000028  r24  = 0xFFFFFFFF8206A068
> !> 00000028  r25  = 0xFFFFFFFF8206A06C
> !> 00000028  r26  = 0xFFFFFFFF8206A070
> !> 00000028  r27  = 0xFFFFFFFF8206A000
> !> 00000028  r28  = 0x0000000000000000
> !> 00000028  r29  = 0x0000000000000000
> !> 00000028  r30  = 0x00000000401CEDD0
> !> 00000028  r31  = 0x000000008206A0AC
> !> 00000028  f0   = 0x4024000000000000 = (double)10.000000 = (float)0.000000
> !> 00000028  f1   = 0x407779A000000000 = (double)375.601563 = (float)0.000000
> !> 00000028  f2   = 0x4059874000000000 = (double)102.113281 = (float)0.000000
> !> 00000028  f3   = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f4   = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f5   = 0xBFF0000000000000 = (double)-1.000000 = (float)0.000000
> !> 00000028  f6   = 0x3F9EB851E0000000 = (double)0.030000 = (float)-36893488147419103232.000000
> !> 00000028  f7   = 0x3FF0000000000000 = (double)1.000000 = (float)0.000000
> !> 00000028  f8   = 0x3CE880FF6993DF95 = (double)0.000000 = (float)22345991471737175285956608.000000
> !> 00000028  f9   = 0xBFC4AF584ABB1D3E = (double)-0.161601 = (float)6131359.000000
> !> 00000028  f10  = 0x3FF0000000000000 = (double)1.000000 = (float)0.000000
> !> 00000028  f11  = 0x4002D97C7F3321D2 = (double)2.356194 = (float)238107416347848357412311999091816005632.000000
> !> 00000028  f12  = 0xC1AA39DDFB49A0E0 = (double)-219999997.643806 = (float)-1046914601210487815814082276223877120.000000
> !> 00000028  f13  = 0x3FC3333340000000 = (double)0.150000 = (float)2.000000
> !> 00000028  f14  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f15  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f16  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f17  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f18  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f19  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f20  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f21  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f22  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f23  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f24  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f25  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f26  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f27  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f28  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f29  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f30  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  f31  = 0x0000000000000000 = (double)0.000000 = (float)0.000000
> !> 00000028  v0   = [0x3A800000, 0x3F800000, 0x3F800000, 0x3F800000]
> !> 00000028  v1   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v2   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v3   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v4   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v5   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v6   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v7   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v8   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v9   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v10  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v11  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v12  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v13  = [0x3F800000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v14  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v15  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v16  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v17  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v18  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v19  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v20  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v21  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v22  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v23  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v24  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v25  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v26  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v27  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v28  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v29  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v30  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v31  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v32  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v33  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v34  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v35  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v36  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v37  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v38  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v39  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v40  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v41  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v42  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v43  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v44  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v45  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v46  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v47  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v48  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v49  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v50  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v51  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v52  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v53  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v54  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v55  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v56  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v57  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v58  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v59  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v60  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v61  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v62  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v63  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v64  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v65  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v66  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v67  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v68  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v69  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v70  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v71  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v72  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v73  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v74  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v75  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v76  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v77  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v78  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v79  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v80  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v81  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v82  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v83  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v84  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v85  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v86  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v87  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v88  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v89  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v90  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v91  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v92  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v93  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v94  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v95  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v96  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v97  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v98  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v99  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v100 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v101 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v102 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v103 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v104 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v105 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v106 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v107 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v108 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v109 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v110 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v111 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v112 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v113 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v114 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v115 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v116 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v117 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v118 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v119 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v120 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v121 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v122 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v123 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v124 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v125 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v126 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
> !> 00000028  v127 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
>

**Comment by gibbed** [comment]
This isn't the place for reporting game-specific issues.

**Pull request merged**
