### PR TITLE
Vulkan Changes

### PR DESCRIPTION
**Pull request by DrChat**
# Texture Cache
* Changed textures from separate images/samplers to combined image samplers
* Planning on not using a shadow copy of physical memory to store textures. GPU support for linear tiling is very limited, and even then may require more memory than what's reserved in the CPU copy of physical memory.
 * We'll queue commands to upload textures to the GPU in their own command buffer, allowing us to support compute shaders/etc. We'll need this to convert textures for any formats not natively supported.

**TO-DO:**
- [x] Texture Uploads
 - [x] Conversion (on CPU)
 - [ ] Decompression (on CPU)
 - [ ] Conversion (on GPU)

# Render Cache
* Changed how we render into EDRAM
 * We can't directly render into EDRAM because GPUs use their own layout for rendering. Instead, I changed it to copy EDRAM contents into temporary render targets, render, and then copy back into the EDRAM buffer.
 * This will break any cases where multiple views are overlapped, and may break cases where the height of the views default to 2560 causing them to overlap.

**TO-DO:**
- [ ] Sort out any issues with overlapping EDRAM views
 - Sort of solved, we sort EDRAM views by their base before uploading back. Still has edge cases.
- [ ] Find a reliable way to get the actual height of a surface
- [ ] Copy and Swap on resolve (low priority)

### CODE REVIEW

**Comment by SakataGintokiYT** [comment]
Any news ?

**Comment by syberphunk** [comment]
Package clang-format-3.8 is currently in debian sid, Jessie only has 3.4

**Comment by SakataGintokiYT** [comment]
@DrChat 
How to build your Xenia Vulkan with new commits  [latest Vulkan PR] on IRC nobody is able to build
-What commands

**Comment by DrChat** [comment]
@SakataGintokiYT Crap - I forgot to add: pass --gpu=vulkan into Xenia's GPU flags.

**Comment by raven02** [comment]
@DrChat , from your preliminary testing using Vulkan backend , any major difference from speed and compatibility prespective ?

**Comment by DrChat** [comment]
At the moment the Vulkan backend is slower/unstable/prone to crashes/etc. Hoping to change that in the future.

**Comment by raven02** [comment]
Thanks for the update . @DrChat

**Comment by SakataGintokiYT** [comment]
@DrChat 
Can you check this log : https://gist.github.com/SakataGintokiYT/708c9a4c1a587cd48662d21335a62738

**Comment by DrChat** [comment]
Whoops - my fault. Thanks for bringing that up.

**Comment by SakataGintokiYT** [comment]
@DrChat 
Fotoszok.pl
Log : https://gist.github.com/SakataGintokiYT/ac0e10e6589be45698fd28d82d3e3142

**Comment by DrChat** [comment]
That's gonna happen on some games for the time being. For now, just try to find games that work.

**Comment by raven02** [comment]
Tested with RR6 and reach in-game .

**Comment by krzysztof860** [comment]
I got this, when I try to launch any game.
xenia error
W10 64bit | Radeon R9 290 - Crimson 16.5.1 | i5 4670k
Log: http://www7.zippyshare.com/v/ppOq7jhQ/file.html

**Comment by SakataGintokiYT** [comment]
^_^
Vulkan c6e905d
@DrChat 
OGL 3 FPS
Vulkan 30 FPS 
Fotoszok.pl

**Comment by Razzile** [comment]
wow vulkan support is moving quick, nice one!

**Comment by DrChat** [comment]
Yeah I'm a bit surprised at the moment - it's faster than the GL backend yet still more unstable.

**Comment by theoldsport** [comment]
>it's faster than the GL backend yet still more unstable

Reminds me of RPCS3's Vulkan implementation - It was originally just a 1:1 port of their GL backend, yet compatibility increased as well as performance

**Comment by raven02** [comment]
@SakataGintokiYT  any build sharing for test ?

**Comment by SakataGintokiYT** [comment]
@raven02 http://www35.zippyshare.com/v/vAQPApaH/file.html

**Comment by Margen67** [comment]
Minecraft goes ingame, but has graphical bugs which aren't in OGL.
mcxeniavulkan

**Comment by Gamedev1909** [comment]
ya something is wrong with your vulkan build my 390x has full vulkan support with all features and yet i get this 
3e5a4e7a-1b5f-11e6-8abe-fc06996962ee

**Comment by Gamedev1909** [comment]
[xenia.txt](https://github.com/benvanik/xenia/files/278852/xenia.txt)

**Comment by Xzip** [comment]
can somebody help me?! i want to play minecraft and i have a question xenia saves the games?

**Comment by DrChat** [comment]
@Gamedev1909 / @krzysztof860 - I'll look into that. I don't think we are even using that feature at the moment.

@Xzip - Please keep the discussion on-topic. But no, Xenia doesn't properly save anything at the moment.

**Comment by Gamedev1909** [comment]
ok can i get a build to test now please with that feature gone and will report back

**Comment by KillzXGaming** [comment]
@SakataGintokiYT can you please build this. I keep getting errors whilist running /xb build on the VS cmd.

**Comment by SakataGintokiYT** [comment]
@KillzXGaming 
@Gamedev1909 
http://www18.zippyshare.com/v/PNZMDUTu/file.html

**Comment by krzysztof860** [comment]
On all games that I have there is "Xenia stopped working" after few seconds. I have newest drivers (16.5.3 on R9 290).
Here are logs of Forza 4, PGR4 and TLoS:DotD
http://www10.zippyshare.com/v/WSMGgsHC/file.html   FM4
http://www10.zippyshare.com/v/gMCHnQZg/file.html   PGR4
http://www10.zippyshare.com/v/WaO3XFIX/file.html   TLoS:DotD

Other games that I've tested are: (Demos) - Burnout Paradise and Revenge, Dirt, DBZ Burst Limit, FM3, Naruto Storm, Ridge Racer 6 (Full versions) - Fez, Minecraft, Banjo Kazooie Nuts and Bolts, FH2.

**Comment by theoldsport** [comment]
@krzysztof860 Many games don't get far in Vulkan yet. The only games in my library that manage to draw 3D in Vulkan before/without crashing are Red Dead, ODST, World at War, Minecraft, and some small XBLA games. Stability will come in time

**Comment by SakataGintokiYT** [comment]
Better graphic by commit a187a49
Dragon Ball Z: Battle of Z
Fotoszok.pl

**Comment by SakataGintokiYT** [comment]
Fotoszok.pl

**Comment by nulcearc** [comment]
Is it working on AMD cards?

**Comment by elfogames** [comment]
Valiant Hearts: The Great War
Vulkan:
vulk
OpenGL:
gl

**Comment by raven02** [comment]
Vulkan one looks right

**Comment by raven02** [comment]
Looks like most of the game boot okay without much error , only color issue.

**Comment by elfogames** [comment]
you might want to use the latest build

http://www118.zippyshare.com/v/phex3Qma/file.html

**Comment by Gamedev1909** [comment]
it's still now working at all on amd please fix this issues or look into it when you have time 
[xenialog390x.txt](https://github.com/benvanik/xenia/files/287688/xenialog390x.txt)

**Comment by ScorchEmber256** [comment]
Whoa! The vulkan builds are coming along nice. If smooth model animations and RGB <---> BGR textures are fixed, then this would be far superior than OpenGL. Keep up the good work and keep those unofficial builds coming!!!  :)

**Comment by Gamedev1909** [comment]
Yup we just need to work out AMD issues and it will be good for all sides

**Comment by DrChat** [comment]
Sorry - I'd work on fixing AMD cards if I had one, but I don't.

**Comment by Gamedev1909** [comment]
well i will continue to provide logs and if you ever need to do work with amd tell me you can high jack my pc

**Comment by Razyre** [comment]
This is why Xenia needs donations, then we could donate and primary developers can eat food and pay for test hardware :^)

**Comment by hlide** [comment]
you mean "can drink beers" ? not sure it would be a good idea :p.

**Comment by DrChat** [comment]
Drunk me is a better coder than sober me ever could be!

**Comment by Razyre** [comment]
You could spend it on whatever you like, drugs for all I care, so long as whatever it is benefited the development of the emulator ;)

**Comment by Gamedev1909** [comment]
https://discord.gg/0u6If6M5qwc9Ipkw if anyone want to chat in real time or share vulkan builds feel free to join the discord and DrChat you are very welcome and would be made admin on the spot

**Comment by elfogames** [comment]
Super Street Fighter 2 Turbo HD Remix
gggg
shd

**Comment by elfogames** [comment]
@Xzip @DrChat it does save
save16

**Comment by SakataGintokiYT** [comment]
@DrChat   How to buid in appveyor ?

**Comment by raven02** [comment]
Just wonder if possible to add AppVeyor build

**Comment by elfogames** [comment]
Nice One
minecraft is better now
sonic 4 ep 1 isn't freezing while the the game stil "running" and the perfomance got better
valiant hearts is fixed and better than OpenGL Now!

gg
s2drchat

**Comment by Margen67** [comment]
@elfogames Can you give me a link to your build?

**Comment by SakataGintokiYT** [comment]
@Margen67 --> http://www24.zippyshare.com/v/nRGAbG6A/file.html

Log : Naruto: Rise of a Ninja  [Nvidia driver crash] : http://www75.zippyshare.com/v/v4vLHwxA/file.html

Log: Naruto - The Broken Bond : [Black screen with sound ] : http://www75.zippyshare.com/v/qUktUBi2/file.html

**Comment by Gamedev1909** [comment]
it still crashes on every game for amd

**Comment by Gamedev1909** [comment]
[xenialogamd.txt](https://github.com/benvanik/xenia/files/299413/xenialogamd.txt)

another long from another build for amd gpu's please take a look

**Comment by DrChat** [comment]
Let's move discussion over to #578.

**Pull request merged**
